"""
Django settings for AnimalResucueApp project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env(env_path):
    if not env_path.exists():
        return

    lines = env_path.read_text(encoding='utf-8').splitlines()
    index = 0
    while index < len(lines):
        line = lines[index].strip()
        index += 1

        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()

        if value == '(':
            collected = []
            while index < len(lines):
                next_line = lines[index].strip()
                index += 1
                if next_line == ')':
                    break
                collected.append(next_line)
            value = ''.join(collected).strip()

        value = value.strip().strip('"').strip("'")
        if key and value and key not in os.environ:
            os.environ[key] = value


load_local_env(BASE_DIR / '.env')


def clean_env_url(value):
    value = (value or '').strip()
    if value.startswith('(') and value.endswith(')'):
        value = value[1:-1].strip()
    return value.strip().strip('"').strip("'").rstrip('/')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7jcly(x*f36ftqfrk%+ptp!my*es@dt5c5v*dwl3cp*!=bbm+d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AnimalRes'
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AnimalResucueApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AnimalResucueApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'AnimalRescueApp',
#         'HOST':'db-mysql-blr1-74221-do-user-14553240-0.b.db.ondigitalocean.com',
#         'PORT':'25060',
#         'USER':'sahu',
#         'PASSWORD':'AVNS_P84CetQ7qPBorl1-gHj'
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pfa',
        'HOST':'pg-2a001833-sallubhoi01-a8e7.i.aivencloud.com',
        'PORT':20470,
        'USER':'avnadmin',
        'PASSWORD':'AVNS_Xj4xQE-ol1eWfYjyQuF'
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AWS_ACCESS_KEY_ID = 'DO00CEXHQL2U2G4B4X3L'
# AWS_SECRET_ACCESS_KEY = 'KYr7Dd0iYZcm+L/fPYTPB5AJh7TgdnIOlFBaRBxSzTU'
# AWS_STORAGE_BUCKET_NAME = 'animalrescuesresources'
AWS_ACCESS_KEY_ID = 'DO00FQ4TDE2GFWDATZJJ'
AWS_SECRET_ACCESS_KEY = 'hQBH/J6y152sMUa95H1XntlWAmCSwu4GVpXZTg4lKs4'
AWS_STORAGE_BUCKET_NAME = 'animalrescuesresources-space'
AWS_S3_ENDPOINT_URL = 'https://blr1.digitaloceanspaces.com'
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
    "ACL": "public-read"
}
AWS_LOCATION = 'resources'


STATIC_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Cloudflare R2 image storage for new rescue uploads.
# Keep credentials in environment variables:
#   CLOUDFLARE_R2_ACCESS_KEY_ID
#   CLOUDFLARE_R2_SECRET_ACCESS_KEY
CLOUDFLARE_R2_ENDPOINT_URL = os.environ.get(
    'CLOUDFLARE_R2_ENDPOINT_URL',
    'https://223b9beadfcbec1aad420de245a03869.r2.cloudflarestorage.com',
)
CLOUDFLARE_R2_BUCKET_NAME = os.environ.get('CLOUDFLARE_R2_BUCKET_NAME', 'pfa')
CLOUDFLARE_R2_ACCESS_KEY_ID = os.environ.get('CLOUDFLARE_R2_ACCESS_KEY_ID', '')
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.environ.get('CLOUDFLARE_R2_SECRET_ACCESS_KEY', '')
CLOUDFLARE_R2_ENDPOINT_URL = clean_env_url(CLOUDFLARE_R2_ENDPOINT_URL)
CLOUDFLARE_R2_PUBLIC_BASE_URL = os.environ.get(
    'CLOUDFLARE_R2_PUBLIC_BASE_URL',
    f'{CLOUDFLARE_R2_ENDPOINT_URL}/{CLOUDFLARE_R2_BUCKET_NAME}',
)
CLOUDFLARE_R2_PUBLIC_BASE_URL = clean_env_url(CLOUDFLARE_R2_PUBLIC_BASE_URL)


logoFaviconUrl = "https://upload.wikimedia.org/wikipedia/en/5/56/People_for_Animals_Official_Logo.png"
logoUrl = "https://upload.wikimedia.org/wikipedia/en/5/56/People_for_Animals_Official_Logo.png"
