# Generated by Django 3.2.19 on 2023-12-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalRescued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('pickup_latitude', models.CharField(max_length=100, null=True)),
                ('pickup_longitude', models.CharField(max_length=100, null=True)),
                ('pickup_landmark', models.CharField(max_length=100, null=True)),
                ('pickup_animalPhoto', models.CharField(max_length=100, null=True)),
                ('pickup_status', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('release_time', models.TimeField(null=True)),
                ('release_latitude', models.CharField(max_length=100, null=True)),
                ('release_longitude', models.CharField(max_length=100, null=True)),
                ('release_landmark', models.CharField(max_length=100, null=True)),
                ('release_animalPhoto', models.CharField(max_length=100, null=True)),
                ('release_status', models.CharField(max_length=100, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalRes.animal')),
            ],
        ),
    ]
