# Generated by Django 3.2.19 on 2023-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0002_animal_animalrescued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrescued',
            name='pickup_animalPhoto',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
