# Generated by Django 3.2.19 on 2023-12-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0003_alter_animalrescued_pickup_animalphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrescued',
            name='release_animalPhoto',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
