# Generated by Django 3.2.19 on 2023-12-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0004_alter_animalrescued_release_animalphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrescued',
            name='distance_variance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
