# Generated by Django 3.2.19 on 2023-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0005_animalrescued_distance_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrescued',
            name='animal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
