# Generated by Django 3.2.19 on 2023-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0006_alter_animalrescued_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pic_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
