# Generated by Django 3.2.19 on 2023-12-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalRes', '0007_animal_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuers',
            name='loginCode',
        ),
        migrations.AlterField(
            model_name='rescuers',
            name='userName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
